### ISSUE TITLE
Testing for new release.

### ISSUE THREAD

**Issue by slackstone** [backdrop-contrib/resource_conflict#1]
Since I closed out the initial Project Port notice issue ([https://github.com/backdrop-ops/contrib/issues/691](https://github.com/backdrop-ops/contrib/issues/691)), I figured I'd run an issue for final testing prior to a first release.

Things are looking very promising, my testing is looking good and I'm getting expected conflicts for my basic reservations. 
I want to buy a few days before we release so I can review all the code changes, look at some possible documentation updates and generally just kick the tires.  (**I'm so happy to have this in a working state.**)

**Comment by argiepiano** [comment]
Sounds good @slackstone! Feel free to take as much time as needed. It'd be great to have better documentation etc. Once ready let me know and we can proceed with the release.

**Comment by yorkshire-pudding** [comment]
Hi @slackstone - how is this testing going? I might give it a test shortly as I'm interested in using this.

**Comment by yorkshire-pudding** [comment]
Hi @slackstone and @argiepiano . I've given this a bit of a test and it does seem to work well.  I think it is probably ready for release.
It would probably make sense to copy this node: https://drupal.org/node/2090487 to the wiki (with a link and acknowledgement of the original source as we don't know how long it will be there. It will also enable documentation to be built on with a Backdrop focus.

**Comment by argiepiano** [comment]
Thanks, @yorkshire-pudding. I've done a release and added the Wiki help.
